apiVersion: apps/v1
kind: Deployment
metadata:
  name: pika-assignment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pika-assignment
  template:
    metadata:
      labels:
        app: pika-assignment
    spec:
      containers:
        - name: pika-assignment-app
          image: pika-assignment:latest
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
