apiVersion: v1
kind: Service
metadata:
  name: pika-assignment-app
spec:
  selector:
    app: pika-assignment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
